---
deployment:
  tasks:
    - export DEPLOYPATH=/home/telegrammbot/public_html
    - /bin/cp /home/telegrammbot/rep/blueyard/index.html $DEPLOYPATH
    - /bin/cp /home/telegrammbot/rep/blueyard/bundle $DEPLOYPATH
    - /bin/cp /home/telegrammbot/rep/blueyard/assets $DEPLOYPATH
